# File: src/nutrition_agent/models/diet_plan.py
"""Diet plan models for final nutrition output."""

from typing import Literal

from pydantic import BaseModel, Field

from src.shared.enums import MealTime


class Macronutrients(BaseModel):
    """Daily macronutrient breakdown by percentage and absolute grams.

    This model is used in both Meal (per-meal macros) and DietPlan (daily totals).
    All percentages are 0-100 and should sum to ~100%.

    Units:
    - *_percentage: percentage of total calories (0-100)
    - *_grams: grams

    Example:
        >>> macros = Macronutrients(
        ...     protein_percentage=30.0,
        ...     protein_grams=150.0,
        ...     carbs_percentage=40.0,
        ...     carbs_grams=200.0,
        ...     fat_percentage=30.0,
        ...     fat_grams=66.7,
        ... )
    """

    protein_percentage: float = Field(
        ...,
        ge=0,
        le=100,
        description="Protein as percentage of total calories (0-100%)",
        examples=[25.0, 30.0, 35.0],
    )
    protein_grams: float = Field(
        ...,
        ge=0,
        le=500,
        description="Protein in grams",
        examples=[100.0, 150.0, 175.0],
    )
    carbs_percentage: float = Field(
        ...,
        ge=0,
        le=100,
        description="Carbohydrates as percentage of total calories (0-100%)",
        examples=[40.0, 45.0, 50.0],
    )
    carbs_grams: float = Field(
        ...,
        ge=0,
        le=800,
        description="Carbohydrates in grams",
        examples=[150.0, 200.0, 250.0],
    )
    fat_percentage: float = Field(
        ...,
        ge=0,
        le=100,
        description="Fat as percentage of total calories (0-100%)",
        examples=[20.0, 25.0, 30.0],
    )
    fat_grams: float = Field(
        ...,
        ge=0,
        le=300,
        description="Fat in grams",
        examples=[50.0, 66.7, 75.0],
    )


class MealNotice(BaseModel):
    """Per-meal validation notice for HITL display.

    Severity thresholds:
    - warning: 2-5% off calorie budget (within tolerance but notable)
    - error: >5% off budget (only reaches HITL when retries exhausted)
    """

    severity: Literal["warning", "error"]
    message: str
    deviation_pct: float = Field(ge=0, le=100)


class Ingredient(BaseModel):
    """Structured ingredient with nutritional data.

    Each ingredient tracks its name, display quantity, weight in grams,
    and kilocalories. The peso_gramos + nombre fields are compatible with
    IngredientInput from the RAG tool (src/nutrition_agent/models/tools.py).

    Example:
        >>> ing = Ingredient(
        ...     nombre="Pechuga de pollo",
        ...     cantidad_display="200g",
        ...     peso_gramos=200.0,
        ...     kcal=330.0,
        ... )
    """

    nombre: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Nombre del ingrediente (ej: 'Pechuga de pollo')",
    )
    cantidad_display: str = Field(
        ...,
        min_length=1,
        max_length=50,
        description="Cantidad legible (ej: '200g', '4 unidades')",
    )
    peso_gramos: float = Field(
        ...,
        ge=0,
        le=2000,
        description="Peso en gramos para calculo nutricional",
    )
    kcal: float = Field(
        ...,
        ge=0,
        le=1500,
        description="Kilocalorias de este ingrediente en la cantidad especificada",
    )

    @property
    def display_text(self) -> str:
        """Human-readable format: '200g de Pechuga de pollo (330 kcal)'."""
        return f"{self.cantidad_display} de {self.nombre} ({self.kcal:.0f} kcal)"


class Meal(BaseModel):
    """Individual meal recipe with macronutrient breakdown.

    Generated by the recipe_generation node and reviewed via HITL (meal_review node).
    Each meal includes structured ingredients with per-ingredient kcal,
    preparation steps, and caloric information.

    Example:
        >>> meal = Meal(
        ...     meal_time=MealTime.DESAYUNO,
        ...     title="Omelet de Proteina",
        ...     description="Omelet de 3 huevos con espinaca y queso",
        ...     total_calories=350.0,
        ...     ingredients=[
        ...         Ingredient(
        ...             nombre="Huevo entero",
        ...             cantidad_display="3 unidades (150g)",
        ...             peso_gramos=150.0, kcal=214.5,
        ...         ),
        ...         Ingredient(
        ...             nombre="Espinaca",
        ...             cantidad_display="100g",
        ...             peso_gramos=100.0, kcal=23.0,
        ...         ),
        ...         Ingredient(
        ...             nombre="Queso bajo en grasa",
        ...             cantidad_display="30g",
        ...             peso_gramos=30.0, kcal=112.5,
        ...         ),
        ...     ],
        ...     preparation=["Batir huevos", "Cocinar", "Servir"],
        ...     alternative="Pancakes proteicos si no hay huevos",
        ... )
    """

    meal_time: MealTime = Field(
        ...,
        description="Meal time category: Desayuno, Almuerzo, Comida, Cena, or Snack",
        examples=[MealTime.DESAYUNO, MealTime.COMIDA, MealTime.CENA],
    )
    title: str = Field(
        ...,
        min_length=5,
        max_length=150,
        description="Meal name/title (5-150 characters)",
        examples=["Omelet de Proteina", "Pechuga de Pollo Asada", "Ensalada Cesar"],
    )
    description: str = Field(
        ...,
        min_length=10,
        max_length=500,
        description="Brief meal description (10-500 characters)",
        examples=[
            "Omelet de 3 huevos con espinaca y queso bajo en grasa",
            "Pechuga asada con vegetales al vapor",
        ],
    )
    total_calories: float = Field(
        ...,
        ge=0,
        le=2000,
        description="Total calories in meal (0-2000 kcal)",
        examples=[350.0, 500.0, 750.0],
    )
    ingredients: list[Ingredient] = Field(
        ...,
        min_length=1,
        description=(
            "Structured ingredients with per-ingredient kcal. "
            "The sum of all ingredient kcal MUST equal "
            "total_calories (±0.5 kcal)."
        ),
    )
    preparation: list[str] = Field(
        ...,
        min_length=1,
        description="Preparation steps (numbered/ordered)",
        examples=[
            [
                "Batir huevos",
                "Cocinar en sarten antiadherente",
                "Agregar espinaca y queso",
            ],
            ["Sazonar pechuga", "Asar a 200°C por 20 minutos", "Servir con vegetales"],
        ],
    )
    alternative: str | None = Field(
        default=None,
        description="Optional alternative meal suggestion if ingredients unavailable",
        examples=[
            "Pancakes proteicos si no hay huevos disponibles",
            "Filete de tilapia al horno como alternativa",
        ],
    )


class ShoppingListItem(BaseModel):
    """Individual shopping list item with quantity.

    Consolidated from all meals and used in DietPlan shopping_list.
    Compatible with consolidate_shopping_list tool.

    Example:
        >>> item = ShoppingListItem(
        ...     food="Huevo",
        ...     quantity="18 unidades (1800g)"
        ... )
    """

    food: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Ingredient name (2-100 characters)",
        examples=["Huevo", "Pechuga de pollo", "Espinaca fresca"],
    )
    quantity: str = Field(
        ...,
        description="Quantity with unit (e.g., '200g', '1 litro', '6 unidades')",
        examples=["200g", "1 litro", "6 unidades", "1800g (18 unidades)"],
    )


class DietPlan(BaseModel):
    """Final daily diet plan with all meals and macronutrient breakdown.

    Assembled by the validation node after all meals have been approved
    (or skipped if user selected 'skip_all' in HITL).

    Example:
        >>> plan = DietPlan(
        ...     diet_type="Alta en Proteina",
        ...     total_calories=2000.0,
        ...     macronutrients=Macronutrients(
        ...         protein_percentage=30.0,
        ...         protein_grams=150.0,
        ...         carbs_percentage=40.0,
        ...         carbs_grams=200.0,
        ...         fat_percentage=30.0,
        ...         fat_grams=66.7,
        ...     ),
        ...     daily_meals=[meal1, meal2, meal3],
        ...     shopping_list=[item1, item2, item3],
        ...     day_identifier=1,
        ... )
    """

    diet_type: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Type of diet (e.g., 'High Protein', 'Keto', 'Balanced')",
        examples=["Alta en Proteina", "Cetogenica", "Balanceada"],
    )
    total_calories: float = Field(
        ...,
        ge=500,
        le=10000,
        description="Total daily calories (500-10000 kcal)",
        examples=[1800.0, 2000.0, 2500.0],
    )
    macronutrients: Macronutrients = Field(
        ...,
        description="Daily macronutrient breakdown",
    )
    daily_meals: list[Meal] = Field(
        ...,
        min_length=1,
        max_length=6,
        description="List of meals for the day (1-6 meals)",
    )
    shopping_list: list[ShoppingListItem] = Field(
        ...,
        description="Consolidated shopping list from all meals",
    )
    day_identifier: int = Field(
        ...,
        ge=1,
        description="Day number in the multi-day plan (e.g., 1, 2, 3...)",
        examples=[1, 2, 3, 7],
    )

    class Config:
        """Pydantic model configuration."""

        json_schema_extra = {
            "example": {
                "diet_type": "Alta en Proteina",
                "total_calories": 2000.0,
                "macronutrients": {
                    "protein_percentage": 30.0,
                    "protein_grams": 150.0,
                    "carbs_percentage": 40.0,
                    "carbs_grams": 200.0,
                    "fat_percentage": 30.0,
                    "fat_grams": 66.7,
                },
                "daily_meals": [
                    {
                        "meal_time": "Desayuno",
                        "title": "Omelet de Proteina",
                        "description": "Omelet de 3 huevos con espinaca y queso",
                        "total_calories": 350.0,
                        "ingredients": [
                            {
                                "nombre": "Huevo entero",
                                "cantidad_display": "3 unidades (150g)",
                                "peso_gramos": 150.0,
                                "kcal": 214.5,
                            },
                            {
                                "nombre": "Espinaca",
                                "cantidad_display": "100g",
                                "peso_gramos": 100.0,
                                "kcal": 23.0,
                            },
                            {
                                "nombre": "Queso bajo en grasa",
                                "cantidad_display": "30g",
                                "peso_gramos": 30.0,
                                "kcal": 112.5,
                            },
                        ],
                        "preparation": ["Batir huevos", "Cocinar", "Servir"],
                        "alternative": None,
                    }
                ],
                "shopping_list": [
                    {"food": "Huevo", "quantity": "18 unidades"},
                    {"food": "Espinaca fresca", "quantity": "300g"},
                ],
                "day_identifier": 1,
            }
        }
